# Base URL
baseurl: /

# Site live URL
url: https://amartyasinha.github.io

# Localhost
#url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: "amartyasinha"
  # Little description about your site
  meta_description:
    Linux
    DevOps
    OpenStack
    RedHat
    Virtualization
    Technology
    Automation
  basetheme: theme-base-01 # pre defined themes are darken, blue-water, redish.
  author: # Author details
    name: Amartya Sinha
    email: amartyasinha918@gmail.com
    url: https://amartyasinha.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key:

  # Profile links, leave blank to ignore
  social:
    github: amartyasinha
    linkedin: amartyasinha918
    credly: amartyasinha
    rss: feed.xml
    talks: talks
# Conversion / Build settings
  show_disclaimer: true

markdown: kramdown

# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink: pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - backup

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

# Add support for the feed talks
plugins:
  - jekyll-feed
  - jekyll-sitemap
feed:
  path: feed.xml

#Read time is based on the average reading speed of an adult
#(roughly 200 WPM). We take the total word count of a post
#and translate it into minutes. The +1 accounts for decimal loss.
#
#(word_count/200) + 1 minute
